### PR TITLE
Give admin team permission to download logs

### PR DESCRIPTION
**Pull request by thomasyu888**

### CODE REVIEW

**Comment by tschaffter** [comment]
This PR enables members of the "EHR Challenge Admins" (list of members: https://www.synapse.org/#!Team:3386536) to access the logs pushed to Synapse by the SynapseWorkflowHook running currently on NCATS and UW server. The logs of the hook do not contains log printed by the models submitted by participants. This PR was requested by @trberg.

As this PR involves information leaving the UW server, I want @trberg and @jprosser to review and accept this PR.

**Comment by tschaffter** [comment]
@trberg @jprosser Please see my comment above and review this PR. Thanks!

**Review by jprosser — APPROVED** [review]
As far as I can tell after chatting with Tim, this is likely fine.

**Review by trberg — APPROVED** [review]
Talked with Justin, we both agree these look good.

**Comment by tschaffter** [comment]
Thanks! @thomasyu888 It all good to merge!

**Pull request merged**
